### ISSUE TITLE
There is a way to avoid database migration on container creation?

### ISSUE THREAD

**Issue by RobertoCesar** [bitnami/bitnami-docker-redmine#151]
**Description**

I'm using bitnami-docker-redmine, tag 4.1.1 and it works fine, but it takes some time to create a container, because everytime the container is created, it migrates the data.

I have seen in the documentation of another redmine docker image (https://hub.docker.com/_/redmine) the possibility to use the environment variable REDMINE_NO_DB_MIGRATE, to avoid the migration step when a container is created.
There is a way to do it using the bitnami image  from this repository. Or some other way to reach this goal)?

Thanks!

**Comment by juan131** [comment]
Hi @RobertoCesar 

I am afraid that's not possible at this very moment. The current logic tries to run the `rake db:migrate` command every time the container is started.

> There is a way to do it using the bitnami image from this repository. Or some other way to reach this goal)?

Thanks so much for your sharing this. I think it's worth including it. I created a task and added it to our backlog to implement a way to skip this migration when required.

**Comment by RobertoCesar** [comment]
Hi @juan131 

I'll be happy! In my opinion there is no sense in make a migration everytime the container starts and it compromises performance.

Thanks for your reply and for consider the request for the backlog!

**Comment by marcosbc** [comment]
Hi, FYI we recently released a new container version, [4.2.1-debian-10-r70](https://github.com/bitnami/bitnami-docker-redmine#421-debian-10-r70). The initialization logic has received a major refactor, and its scripts are now located in the [`rootfs/` directory](https://github.com/bitnami/bitnami-docker-redmine/blob/master/4/debian-10/rootfs/).

Now that the initialization scripts are open-sourced in this repository, it would be great if you wanted to contribute the changes to support this feature. Any contributions are welcome and we'll be glad to help with the release.

**Comment by carrodher** [comment]
Hi, unfortunately, if the issue is not solved in recent versions means the task is still on our backlog and there are no plans to work on it in the short/middle term.

In the same way, please, [note the Bitnami team is not actively working on new features/improvements nor providing support through GitHub Issues for this project](https://github.com/bitnami/bitnami-docker-redmine#community-supported-solution) since this asset was marked as a “Community supported solution”.

At this point, the best option to fix any issue or add a new feature is to contribute create a PR; the Bitnami team will be happy to review it and provide feedback.
