### ISSUE TITLE
Add support for Mercurial and SVN

### ISSUE THREAD

**Issue by fbu31** [bitnami/bitnami-docker-redmine#167]
In this image, only git is supported.
Can you add support for mercurial and svn?

**Comment by miguelaeh** [comment]
Hi @fbu31 ,
Could you provide more details why they are needed?
We try to maintain the images as small as possible, but you can always customize the Dockerfile and add something like 
```
RUN install_packages mercurial
```

**Comment by fbu31** [comment]
Hi miguelaeh,
I'm using mercurial repositories and I think it would be nice if mercurial commands is supported directly in Redmine.
Thanks for your answer, I will try your solution.

**Comment by miguelaeh** [comment]
Hi @fbu31 ,
We have no plans to add mercurial soon, but we can leave this ticket open in case more people request it.

**Comment by pablogalegoc** [comment]
Hi @fbu31,

I'm leaving this open as @miguelaeh said in case there are more requests about Mercurial and SVN

**Comment by carrodher** [comment]
Hi, unfortunately, if the issue is not solved in recent versions means the task is still on our backlog and there are no plans to work on it in the short/middle term.

In the same way, please, [note the Bitnami team is not actively working on new features/improvements nor providing support through GitHub Issues for this project](https://github.com/bitnami/bitnami-docker-redmine#community-supported-solution) since this asset was marked as a “Community supported solution”.

At this point, the best option to fix any issue or add a new feature is to contribute create a PR; the Bitnami team will be happy to review it and provide feedback.
