### ISSUE TITLE
Access to /opt/bitnami/redmine/public folder from outside container

### ISSUE THREAD

**Issue by Ermesx** [bitnami/bitnami-docker-redmine#66]
Hi,

I would like to access to /opt/bitnami/redmine/public because I want to add new themes and images to customize redmine.

What should I do to expose whole directory or specific directories inside as volumes with access from host system.

**Comment by prydonius** [comment]
Hey @Ermesx, the mount point you're looking for is `/bitnami/redmine`, which exposes configuration, uploads, plugins and the public folder for persistence. Using the Compose file in this repo, a local docker volume is created for this directory, but in order to change this to a host mount you can follow the instructions for [mounting host directories as data volumes](https://github.com/bitnami/bitnami-docker-redmine#mount-host-directories-as-data-volumes-with-docker-compose). You may need to backup your existing data before switching the host mount, using the [backup and restore instructions](https://github.com/bitnami/bitnami-docker-redmine#backing-up-your-application).

Hope this helps.

**Comment by fturiot** [comment]
hi,
i have add themes in public theme bu not read after restart , not themes in the list .
What user and right in this folder themes ?
for plugin it is ok
regards 
fred

**Comment by sameersbn** [comment]
@prydonius unfortunately the themes directory is not exposed to the user on the volume

@Ermesx @fturiot You can follow these instructions to install themes,

1. Install the theme in a directory under `public/themes/`

```bash
sudo mkdir -p /path/to/host/redmine/volume/public/themes/minelab
wget https://github.com/hardpixel/minelab/archive/v0.2.tar.gz -O - | sudo tar -zvxf - --strip=1 -C /path/to/host/redmine/volume/public/themes/minelab
sudo chown -R 1000:1001 /path/to/host/redmine/volume/public/themes
```

_Please replace `/path/to/host/redmine/volume` accordingly_

2. Create a symlink in `/opt/bitnami/redmine/public/themes/` to the theme in `/bitnami/redmine/public/themes/`, this is a workaround:

```bash
docker exec -it <REDMINE-CONTAINER-ID> ln -sf /bitnami/redmine/public/themes/minelab /opt/bitnami/redmine/public/themes/
```

**PS. This step will need to be executed each time the redmine container is re-created**

Now you should see the `minelab` them being listed in the theme selection dialog.

We will work on fixing this issue and ping you guys again when the fix is available in a release.

**Comment by pbredenberg** [comment]
I can confirm the solution presented by @sameersbn works, and because I am testing out a bunch of Redmine themes right now, I created a brief bash script in this gist to make this a little quicker: https://gist.github.com/pbredenberg/f05e5b3a6c03fbbe5c479e6b655d06c3

Instructions in a comment.

I am very interested in seeing new support as you mention! Thanks for the hard work on this project thus far.

**Comment by devkev16** [comment]
Hi,

I faced the same issue as op and I also found the directory /opt/bitnami/redmine. I got the /bitnami/redmine in my compose-file as a volume. When I do changes in the volume directory this does not get copied to the /opt/... directory.

So my question is: Should'nt the default volume mounted on /opt/bitnami/redmine instead of /bitnami/redmine or is there a script one have to run to transfer the files? (If, then it would conflict with the purpose of a volume I think, the changes you do in a volume should be transfered into the container like "themes" as op says and one did not have to run an extra script to do this).

Hope you understand my bad english!

**Comment by juan131** [comment]
Hello @devkev16 

The main reason why is not mounted by default at `/opt/bitnami/redmine` is that we only backup the "data & configuration" files at the volume so we can deploy upgrades easily following the approach explained at:
https://github.com/bitnami/bitnami-docker-redmine#upgrade-this-application

That's why only those kind of files are stored at `/bitnami/redmine/` and included using symbolic links at `/opt/bitnami/redmine`.

**Comment by devkev16** [comment]
Hi @juan131,

thank you for your explanation! 

If I understood right: Wouldn't it be possible to extend the Dockerfile to instruct docker to create a themes-symlink too (after copying the files to the themes directory at /bitnami/redmine/)?

**Comment by juan131** [comment]
@devkev16 we should revisit this for sure.

@prydonius what do you think about including the directory `public/themes` in the list of directories to persist? According to http://www.redmine.org/projects/redmine/wiki/RedmineUpgrade it's recommended to recover the themes that were installed before deploying the upgrade. However it also recommend to update to the latest version of every theme when possible.

We won't update the themes included by default in Redmine if we include it in the list of directories to persist but users will be able to upgrade their images without losing their themes.

**Comment by kirill-zhukov** [comment]
Hi, do we have to stop/start redmine after creating a symlink?

**Comment by kirill-zhukov** [comment]
> Hi, do we have to stop/start redmine after creating a symlink?

OK, found out the link was created wrong. So basically no additional cations needed. The theme is shown in the list immediately.

**Comment by kirill-zhukov** [comment]
It's not mandatory. Please note that you can restart any service inside the container without restarting the container by running the command below inside the container:

nami restart XXXX

Thanks a lot, I guess missed this in docs, this really helps.
Means I can also do:
`docker-composer exec redmine nami restart XXXX`

**Comment by ErmakovDmitriy** [comment]
Hi, 
Could you add some Environment variable flag to enable symlink to Redmine themes?
As I can see, now bitnami/redmine copies only plugin_assets:

```shell
app-entrypoint.sh 11:02:51.38 
app-entrypoint.sh 11:02:51.39 Welcome to the Bitnami redmine container
app-entrypoint.sh 11:02:51.39 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-redmine
app-entrypoint.sh 11:02:51.39 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-redmine/issues
app-entrypoint.sh 11:02:51.39 
nami    INFO  Initializing redmine
redmine DEBUG Creating Redmine System User...
redmine DEBUG ==> Detected MariaDB/MySQL database
redmine INFO  Redmine has been already initialized, restoring...
redmine TRACE [restorePersistedData] Restoring /bitnami/redmine/conf/configuration.yml to /opt/bitnami/redmine/conf/configuration.yml
redmine TRACE [restorePersistedData] Restoring /bitnami/redmine/conf/database.yml to /opt/bitnami/redmine/conf/database.yml
redmine TRACE [restorePersistedData] Restoring /bitnami/redmine/public/plugin_assets to /opt/bitnami/redmine/public/plugin_assets
redmine TRACE [restorePersistedData] Restoring /bitnami/redmine/plugins to /opt/bitnami/redmine/plugins
redmine TRACE [restorePersistedData] Restoring /bitnami/redmine/files to /opt/bitnami/redmine/files
```
I would like to have a possibility to use themes which are stored inside Kubernetes PV using helm stable/redmine chart.

**Comment by juan131** [comment]
Hi @ErmakovDmitriy 

The current persisted directories/files are:

- /opt/bitnami/redmine/conf/configuration.yml
- /opt/bitnami/redmine/conf/database.yml
- /opt/bitnami/redmine/public/plugin_assets
- /opt/bitnami/redmine/plugins
- /opt/bitnami/redmine/files

I guess you want us to add `/opt/bitnami/redmine/public/themes` to this list. 

By default, this folder is not empty (as it's `plugin_assets`):

```console
$ tree public/themes/
public/themes/
├── alternate
│   └── stylesheets
│       └── application.css
├── classic
│   ├── images
│   │   ├── home.png
│   │   └── wrench.png
│   └── stylesheets
│       └── application.css
└── README
```

It comes with the default themes, so we won't be able to upgrade these default themes to the ones packaged on new Redmine versions by simply restarting the container.

@beltran-rubo what do you think? Do you think it's worth to persist the themes (even if we lose the ability to upgrade the default ones)?

**Comment by ErmakovDmitriy** [comment]
Hi, @juan131
I see the point.

Could you think about adding a directory into the container so that all "executable" files inside the directory are started on every container start in alphabetical order?
I think it could solve not only the problem with themes but also provide a very useful way for adding small customizations.

What do you think about it?

As I can see, the idea is implemented in bitnami/postgresql image as `/docker-entrypoint-initdb.d` directory.

**Comment by beltran-rubo** [comment]
Hi,

in that case I think the best way right now is you can create your own container based on the Bitnami Redmine and add an action in the entrypoint to download or copy your theme into that folder, that way you can keep using the latest version of your theme. Would that work for you?

**Comment by ErmakovDmitriy** [comment]
Thank you, @beltran-rubo 
I have just started doing it.

I thought that it could be good for community if the feature existed in the "upstream". 
I believe it will work for me and it will solve another issue for my deployment: #134 

Thank you!

**Comment by juan131** [comment]
Great @ErmakovDmitriy !!
Please do not hesitate to let us know if you need help to customize your own Redmine image.
